# Generated by Django 5.2.12 on 2026-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nipple',
            name='internal_thread_length_mm',
            field=models.FloatField(default=0.0, help_text='Usable threaded bore length along nipple axis from seat toward hub (mm).'),
        ),
    ]
