# Generated by Django 5.2.12 on 2026-03-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('left_flange_pcd_mm', models.FloatField()),
                ('right_flange_pcd_mm', models.FloatField()),
                ('left_flange_offset_mm', models.FloatField(help_text='Wheel center plane to left flange hole circle (mm).')),
                ('right_flange_offset_mm', models.FloatField(help_text='Wheel center plane to right flange hole circle (mm).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nipple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('head_diameter_mm', models.FloatField()),
                ('head_height_mm', models.FloatField(help_text='Axial depth of head inside rim well / counterbore (mm).')),
                ('body_length_mm', models.FloatField(help_text='Overall exposed body beyond rim seat toward hub, for diagram (mm).')),
                ('shank_diameter_mm', models.FloatField(default=4.0, help_text='Body OD at rim interface, schematic (mm).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('erd_mm', models.FloatField(help_text='Effective rim diameter at nipple seat (mm).')),
                ('inner_width_mm', models.FloatField(help_text='Inner width at/near nipple level — schematic cavity width (mm).')),
                ('well_depth_mm', models.FloatField(help_text='Schematic: nipple seat up to cavity roof / brake-surface reference (mm).')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
